apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-microsservice
  namespace: mealrush
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-microsservice
  template:
    metadata:
      labels:
        app: auth-microsservice
    spec:
      containers:
        - name: auth-microsservice
          image: docker.io/lucascrapino/auth-microsservice:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3020
          envFrom:
            - secretRef:
                name: auth-env
          resources:
            limits:
              memory: 256Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-microsservice
  namespace: mealrush
spec:
  selector:
    app: auth-microsservice
  ports:
    - protocol: TCP
      port: 3020
      targetPort: 3020
  type: NodePort