apiVersion: apps/v1
kind: Deployment
metadata:
  name: institution-microsservice
  namespace: mealrush
spec:
  replicas: 1
  selector:
    matchLabels:
      app: institution-microsservice
  template:
    metadata:
      labels:
        app: institution-microsservice
    spec:
      containers:
        - name: institution-microsservice
          image: docker.io/lucascrapino/institution-microsservice:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3005
          envFrom:
            - secretRef:
                name: institution-env
          resources:
            limits:
              memory: 256Mi
              cpu: 1
            requests:
              memory: 256Mi
              cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: institution-microsservice
  namespace: mealrush
spec:
  selector:
    app: institution-microsservice
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
  type: NodePort